version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react
    versions:
    - 0.14.10
  - dependency-name: babelify
    versions:
    - 7.3.0
  - dependency-name: gulp-notify
    versions:
    - 3.2.0
